### ISSUE TITLE
No option to query giphy stickers

### ISSUE THREAD

**Issue by tanvish99** [firstfloorsoftware/giphy_picker#10]
Hello, I was trying to implement giphy stickers, emojis and text but there is no option to provide those parameters.

**Comment by tanvish99** [comment]
![WhatsApp Image 2020-09-08 at 14 48 43](https://user-images.githubusercontent.com/36073418/92458090-9e5cb480-f1e2-11ea-90d6-f3386e8a981e.jpeg)

The Giphy UI sdk for android has this option

**Comment by tanvish99** [comment]
There is now support for stickers but not for the giphy emojis and text.

**Comment by kozw** [comment]
Looks like the Giphy API doesn't support emojis and text. Those are only available in the SDKs (taken from https://developers.giphy.com/docs/sdk#content-types)

**Comment by tanvish99** [comment]
So is there any way to implement the giphy sdk into flutter?

**Comment by kozw** [comment]
Probably not, would require the various SDKs for the different platforms. You might be able to pull it off using platforms channels. There are no plans to do this for this picker. It would essentially replace the entire plugin with the native SDK.

**Comment by tanvish99** [comment]
okay thanks
