### ISSUE TITLE
Require update

### ISSUE THREAD

**Issue by leszekkrol** [firstfloorsoftware/giphy_picker#20]
`Because giphy_picker 1.0.8 depends on http ^0.12.0+2 and no versions of giphy_picker match >1.0.8 <2.0.0, giphy_picker ^1.0.8 requires http ^0.12.0+2.

**Comment by dibyanshuanand** [comment]
@leszekkrol I was facing the same issue and solved it by updating to version 2.0.0-nullsafety.0

**Comment by kozw** [comment]
Just published 2.0.0, all should be good now
