### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by phong764119** [firstfloorsoftware/giphy_picker#3]
the new version is unable to compile
version 1.0.1 is working fine

Compiler message:
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/giphy_picker-1.0.2/lib/src/widgets/giphy_context.dart:40:10: Error: The method 'getElementForInheritedWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getElementForInheritedWidgetOfExactType'.
        .getElementForInheritedWidgetOfExactType<GiphyContext>()

**Comment by kozw** [comment]
What version of flutter are you using? I believe getElementForInheritedWidgetOfExactType is relatively new.

**Comment by phong764119** [comment]
Yeah the new flutter version (v1.12.13+hotfix.5) have some issue with android so i just used v1.9.1+hotfix.6 for now, anyway i just used previous version and it worked for me, thanks you
