### ISSUE TITLE
15mb demo.gif is packing with assets

### ISSUE THREAD

**Issue by zulman** [firstfloorsoftware/giphy_picker#6]
Hello folks,

Thank you for making this amazing package. I've found that demo.gif from assets/ directory is packing into release build. What do you think, is it worth considering to exclude this 15mb file? Thank you :)

**Comment by kozw** [comment]
Valid point! Will look into it

**Comment by kozw** [comment]
fixed in 4808debc357c6c39d8c38abc1c9a6a7e01447275
