### ISSUE TITLE
get the file path of a gif

### ISSUE THREAD

**Issue by Loopex2019** [firstfloorsoftware/giphy_picker#8]
Hi is there a way for getting the file path of a gif ?

**Comment by kozw** [comment]
Not sure what you mean with file path of a gif. When selecting a gif, you'll eventually end up with a [GiphyGif instance](https://pub.dev/documentation/giphy_client/latest/giphy_client/GiphyGif-class.html) of the picked gif. This GiphyGif contains a list of uri's for various image formats and sizes.

You can then perform an HTTP GET of the desired gif image using any of the image uri's, and save the response to disk if required.

**Comment by Loopex2019** [comment]
Ah okay. but i want to send the gif url to a database for example. Should i use `bitlyGifUrl` or the `url` Property .

**Comment by Loopex2019** [comment]
Great i got it
